/* eslint @typescript-eslint/camelcase: ["off"] */

const webdriverConfig = {
    hostname: 'hub.lambdatest.com',
    port: 80,
}

module.exports = config => {
    config.set({
        // Base
        basePath: '.',
        files: [
            'https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js',
            'tests/lib/toast.min.js',
            'tests/tests.js',
        ],
        logLevel: config.LOG_INFO,
        autoWatch: false,
        // Mocha + Chai + Sinon
        frameworks: [
            'mocha',
            'sinon-chai',
        ],
        reporters: ['mocha'],
        client: {
            chai: { includeStack: true },
            clearContext: false, // LambdaTest
        },
        // LambdaTest
        singleRun: true,
        captureTimeout: 600000,
        retryLimit: 1,
        browserDisconnectTimeout: 90000,
        browserDisconnectTolerance: 1,
        browserNoActivityTimeout: 90000,
        concurrency: 1,
        browsers: [
            'lambda_chrome',
            'lambda_firefox',
            /* Disabled: the connection to the server hangs on */
            // 'lambda_edge',
            'lambda_ie11',
            'lambda_ie10',
            /* Disabled: lacks of Uint8Array support, needed by Mocha */
            // 'lambda_ie9',
            /* Disabled: the connection to the server hangs on */
            // 'lambda_safari',
        ],
        customLaunchers: {
            lambda_chrome: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Chrome',
                platform: 'Windows 10',
                version: '71.0',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_firefox: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Firefox',
                platform: 'Windows 10',
                version: '64.0',
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_edge: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Microsoft Edge',
                platform: 'Windows 8.1',
                version: '18.0',
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_ie11: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Internet Explorer',
                platform: 'Windows 10',
                version: '11.0',
                'ie.compatibility': 11001,
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_ie10: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Internet Explorer',
                platform: 'Windows 7',
                version: '10.0',
                'ie.compatibility': 11001,
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_ie9: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Internet Explorer',
                platform: 'Windows 7',
                version: '9.0',
                'ie.compatibility': 11001,
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
            lambda_safari: {
                base: 'WebDriver',
                config: webdriverConfig,
                browserName: 'Safari',
                platform: 'macOS Mojave',
                version: '12.0',
                name: 'Karma With Heartbeat',
                tunnel: true,
                video: false,
                visual: false,
                network: true,
                console: true,
                user: process.env.LT_USERNAME,
                accessKey: process.env.LT_ACCESS_KEY,
                pseudoActivityInterval: 15000,
            },
        },
    })
}
