// https://github.com/karma-runner/karma-browserstack-launcher
// https://www.browserstack.com/automate/capabilities
// https://oligofren.wordpress.com/2014/05/27/running-karma-tests-on-browserstack/
// https://github.com/browserstack/api

const pkg = require('./package.json')

/*
    Karma config
*/
module.exports = config => {
    config.set({
        // ========== Base ==========
        basePath: '.',
        files: [
            'https://cdn.jsdelivr.net/npm/promise-polyfill@8/dist/polyfill.min.js',
            'tests/lib/toast.min.js',
            'tests/utils.js',
            'tests/tests.base.js',
            'tests/tests.css.js',
            'tests/tests.js.js',
            'tests/tests.all.js',
        ],
        logLevel: config.LOG_INFO,
        autoWatch: false,
        singleRun: true,
        concurrency: 4,
        browserDisconnectTimeout : 10 * 1000,
        browserDisconnectTolerance : 1,
        browserNoActivityTimeout : 4 * 60 * 1000,
        captureTimeout : 4 * 60 * 1000,
        retryLimit: 3,
        // ========== Karma + Mocha + Chai + Sinon = <3 ==========
        frameworks: [
            'mocha',
            'sinon-chai',
        ],
        plugins: ['karma-*'],
        reporters: ['mocha', 'dots', 'BrowserStack'],
        client: {
            chai: { includeStack: true },
            captureConsole: true,
        },
        // ========== BrowserStack ==========
        browserStack: {
            username: process.env.BROWSERSTACK_USERNAME,
            accessKey: process.env.BROWSERSTACK_ACCESS_KEY,
        },
        // ========== Browsers ==========
        customLaunchers: {
            chrome: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Chrome',
                os: 'Windows',
                os_version: '10',
                browser: 'chrome',
                browser_version: '83.0',
            },
            firefox: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Firefox',
                os: 'Windows',
                os_version: '10',
                browser: 'firefox',
                browser_version: '76.0',
            },
            edge: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Edge',
                os: 'Windows',
                os_version: '10',
                browser: 'edge',
                browser_version: '83.0',
            },
            safari13: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Safari 13',
                os: 'OS X',
                os_version: 'Catalina',
                browser: 'safari',
                browser_version: '13.1',
            },
            safari12: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Safari 12',
                os: 'OS X',
                os_version: 'Mojave',
                browser: 'safari',
                browser_version: '12.1',
            },
            safari11: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Safari 11',
                os: 'OS X',
                os_version: 'High Sierra',
                browser: 'safari',
                browser_version: '11.1',
            },
            ie11: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Internet Explorer 11',
                os: 'Windows',
                os_version: '7',
                browser: 'ie',
                browser_version: '11.0',
            },
            android10: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 10',
                device: 'Samsung Galaxy S20',
                os: 'android',
                os_version: '10.0',
                browser: 'android',
                real_mobile: true,
            },
            android9: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 9',
                device: 'Samsung Galaxy S9 Plus',
                os: 'android',
                os_version: '9.0',
                browser: 'android',
                real_mobile: true,
            },
            android8: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 8',
                device: 'Samsung Galaxy S9 Plus',
                os: 'android',
                os_version: '8.0',
                browser: 'android',
                real_mobile: true,
            },
            android7: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 7',
                device: 'Samsung Galaxy S8 Plus',
                os: 'android',
                os_version: '7.0',
                browser: 'android',
                real_mobile: true,
            },
            android6: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 6',
                device: 'Samsung Galaxy S7',
                os: 'android',
                os_version: '6.0',
                browser: 'android',
                real_mobile: true,
            },
            android5: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 5',
                device: 'Samsung Galaxy S6',
                os: 'android',
                os_version: '5.0',
                browser: 'android',
                real_mobile: true,
            },
            android44: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'Android 4.4',
                device: 'Samsung Galaxy Note 4',
                os: 'android',
                os_version: '4.4',
                browser: 'android',
                real_mobile: true,
            },
            ios13: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'iOS 13',
                device: 'iPhone XS',
                os: 'ios',
                os_version: '13',
                browser: 'iphone',
                real_mobile: true,
            },
            ios12: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'iOS 12',
                device: 'iPhone XS',
                os: 'ios',
                os_version: '12',
                browser: 'iphone',
                real_mobile: true,
            },
            ios11: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'iOS 11',
                device: 'iPhone X',
                os: 'ios',
                os_version: '11',
                browser: 'iphone',
                real_mobile: true,
            },
            ios10: {
                base: 'BrowserStack',
                project: pkg.name,
                build: `${pkg.name}@${pkg.version}`,
                name: 'iOS 10',
                device: 'iPhone 7',
                os: 'ios',
                os_version: '10',
                browser: 'iphone',
                real_mobile: true,
            },
        },
        browsers: [
            'chrome',
            'firefox',
            'edge',
            'safari13',
            'safari12',
            'safari11',
            'ie11',
            'android10',
            'android9',
            'android8',
            'android7',
            'android6',
            'android5',
            'android44',
            'ios13',
            'ios12',
            'ios11',
            'ios10',
        ],
    })
}
